import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { RouterOutputs, api } from "~/utils/api";

import dayjs from "dayjs";
import Image from "next/image";
import { LoadingSpinner } from "~/components/loading";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return <div className="flex gap-3 w-full">
    <Image src={user.profileImageUrl} alt="Profile Image" className="w-14 h-14 rounded-full" width={56} height={56} />
    <input placeholder="Type some emojis!" className="bg-transparent grow outline-none" />
  </div>
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: { fullPost: PostWithUser }) => {
  const { post, author } = props.fullPost;

  return (
    <div key={post.id} className="flex border-b border-slate-400 p-8 outline-none gap-3">
      <Image src={author.profileImageUrl} className="h-14 w-14 rounded-full" alt={`${author.userName}'s profile picture`} width={56} height={56} />
      <div className="flex flex-col">
        <div className="flex gap-1">
          <span className="font-bold">{author.eMail}</span><span>·</span><span>{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <p>{post.content}</p>
      </div>
    </div>);
};

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  console.log(user?.user?.id);

  if (isLoading) return <LoadingSpinner />;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x h-full border-slate-400">
          <div className="flex border-b border-slate-400 p-4">
            <div className="flex justify-center">
              {!user.isSignedIn && <SignInButton />}
            </div>
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView key={fullPost.post.id} fullPost={fullPost} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
